server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/confectionerydb?serverTimezone=UTC
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update

storage.location: "/image"
